name: azureml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib=3.1.1
  - pandas=1.1.1
  - pip
  - pip:
    - azureml-sdk[automl,notebooks,explain]
    - azuremlftk
    - azure-cli
