name: timeseriesbook
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.9
  - pandas=1.1.2
  - matplotlib=3.3.2
  - scikit-learn=0.23.2
  - statsmodels=0.12.0
  - seaborn=0.11.0
  - xlrd
  - jupyter
  - pip
  - pip:
    - tensorflow==2.3.0
    - pandas-datareader==0.9.0
